# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce3c3045cdab9e3ff1624c78d2220d2217c9d3992cc48c5629c5bd6c474e2dd3bf96c41b1fd6476a06e456d1789e5159677b616b085e1dc3b06bc1d31e50e143

test:
  secret_key_base: 1b5d5d887e5b7f86a4f27a8380cda057d33c158340cb949c89f13e42d157df67a7441c9755403446a36f4af8883dfe43bca1568b2a4d456460268c281b11982a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
